<?php

/**
 * ObservationRevisionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObservationRevisionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObservationRevisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObservationRevision');
    }

    /**
     * Gets pending revisions
     * @return Doctrine_Collection pending ObservationRevision objects
     */
    public static function findPending()
    {
        $query = Doctrine_Query::create()->from('ObservationRevision r')
            ->where('r.status = ?', 'pending')
            ->orderBy('r.requested_at');
        $items = $query->execute();
        return $items;
    }

    /**
     * Gets revisions for an observation, ordered by requested datetime
     */
    public static function findByObservationId($observationId)
    {
        $query = self::getInstance()->createQuery('r')
            ->where('r.observationId = ?', $observationId)
            ->orderBy('r.requested_at DESC');
        $items = $query->execute();
        return $items;
    }

    /**
     * Returns the number of pending items
     */
    public static function getPendingCount()
    {
        $q = Doctrine_Query::create()
            ->select('COUNT(r.id) as count')
            ->from('ObservationRevision r')
            ->where('r.status = ?', 'pending');
        $row = $q->fetchOne(array(), Doctrine_Core::HYDRATE_ARRAY);
        return $row['count'];
    }

}