<?php

/**
 * ObservationRevision
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class ObservationRevision extends BaseObservationRevision
{
    public static function getActionChoices()
    {
        return array(
            'create' => 'Create',
            'edit' => 'Edit',
            'delete' => 'Delete',
        );
    }

    public static function getStatusChoices()
    {
        return array(
            'pending' => 'Pending',
            'accepted' => 'Accepted',
            'rejected' => 'Rejected',
        );
    }

    public function accept($reviewedBy, $comment = null)
    {
        $observation = null;
        if ($this->action == 'create') {
            $observation = new Observation();
            $observationData = json_decode($this->observationData, true);
            $observation->fromArray($observationData);
            $observation->createdAt = date('Y-m-d H:i:s');
            $observation->updatedAt = $observation->createdAt;
            $observation->save();
        }
        else if ($this->action == 'edit') {
            if ($this->observationId !== null) {
                $observation = Doctrine_Core::getTable('Observation')
                    ->findOneBy('id', $this->observationId);
                $observation->updatedAt = date('Y-m-d H:i:s');
            }
            if ($observation === null) {
                $observation = new Observation();
                $observation->createdAt = date('Y-m-d H:i:s');
                $observation->updatedAt = $observation->createdAt;
            }
            $observationData = json_decode($this->observationData, true);
            $observation->synchronizeWithArray($observationData, true);
            $observation->save();
        }
        else if ($action == 'delete') {
            if ($this->observationId !== null) {
                $observation = Doctrine_Core::getTable('Observation')
                    ->findOneBy('id', $this->observationId);
                if ($observation !== null) {
                    $observation->status = 'deleted';
                    $observation->updatedAt = date('Y-m-d H:i:s');
                    $observation->save();
                }
            }
        }

        // save revision information
        $this->observationId = $observation->id;
        $this->reviewedBy = $reviewedBy;
        $this->reviewedAt = date('Y-m-d H:i:s');
        $this->reviewerComment = $comment;
        $this->status = 'accepted';
        $this->save();
    }

    public function reject($reviewedBy, $comment)
    {
        // save revision information
        $this->reviewedBy = $reviewedBy;
        $this->reviewedAt = date('Y-m-d H:i:s');
        $this->reviewerComment = $comment;
        $this->status = 'rejected';
        $this->save();
    }
}