<?php
header("Content-type: text");
header("Content-Disposition: attachment; filename=observations_".date('Y-m-d').".yml");
header("Pragma: no-cache");
header("Expires: 0");

function cleanValue($value) {
    $value = utf8_encode($value);
    $value = str_replace(array("\r\n", "\n", "\r"), ' ', $value);
    return $value; 
}

echo "observations:\n";
foreach ($this->rows as $row) {
    echo "  -\n";
    foreach ($row as $key => $value) {
        if (!is_array($value) && !empty($value)) {
            $value = cleanValue($value); 
            echo "    $key: " . $value . "\n";
        }
    }

    if (count($row['genes']) > 0) {
        $skipKeys = array('observationId', 'geneId');
        echo "    genes:\n";
        foreach ($row['genes'] as $gene) {
           echo "      -\n";
           foreach ($gene as $key => $value) {
                if (!is_array($value) && !in_array($key, $skipKeys) && !empty($value)) {
                    $value = cleanValue($value); 
                    echo "        $key: ".$value."\n";
                }
            }
        }
    }

    if (count($row['compounds']) > 0) {
        $skipKeys = array('observationId', 'compoundId');
        echo "    compounds:\n";
        foreach ($row['compounds'] as $gene) {
           echo "      -\n";
           foreach ($gene as $key => $value) {
                if (!is_array($value) && !in_array($key, $skipKeys) && !empty($value)) {
                    $value = cleanValue($value); 
                    echo "        $key: ".$value."\n";
                }
            }
        }
    }

    if (count($row['environments']) > 0) {
        $skipKeys = array('observationId', 'environmentId');
        echo "    environments:\n";
        foreach ($row['environments'] as $item) {
           echo "      -\n";
           foreach ($item as $key => $value) {
                if (!is_array($value) && !in_array($key, $skipKeys) && !empty($value)) {
                    $value = cleanValue($value); 
                    echo "        $key: ".$value."\n";
                }
            }
        }
    }

}
