<table class="dataTable" style="width:100%">
    <thead>
        <tr>
            <th>GO Term</th>
            <th>Term</th>
            <th>Category</th>
            <th>Evidence</th>
        </tr>
    </thead>

    <?php foreach ($this->rows as $row): ?>
        <tr>
            <td>
                <a href="http://amigo.geneontology.org/cgi-bin/amigo/term-details.cgi?term=<?php
                    echo $row['goId'] ?>">
                    <?php echo $row['goId'] ?>
                </a>
            </td>
            <td><?php echo $row['term'] ?></td>
            <td><?php echo $row['category'] ?></td>
            <td><?php echo $row['evidence'] ?></td>
        </tr>
    <?php endforeach ?>
</table>