<table style="margin: 0 auto">
    <?php foreach ($this->homologs as $species => $homologs): ?>
        <tr>
            <td style="vertical-align: top; padding-right:1em">
                <em style="white-space:nowrap"><?php echo $species ?>:</em>
            </td>
            <td>
                <?php foreach ($homologs as $homolog): ?>
                    <a href="<?php echo $this->baseUrl()
                         .'/genes/show/id/'.$homolog['ncbiGeneId'] ?>"
                         ><?php echo $homolog['symbol'] ?></a>
                <?php endforeach ?>
            </td>
        </tr>
    <?php endforeach ?>
</table>