<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/jquery-1.4.2.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/advancedSearchForm.js') ?>

<div style="margin-right: 420px">
<form name="searchForm" action="<?php echo $this->element->getAction() ?>" 
      method="<?php echo $this->element->getMethod() ?>">

    <?php if ($this->element->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <fieldset style="padding:1em;">
        <legend>Observation:</legend>

        <table class="formTable">
            <tr>
                <th><?php echo $this->element->search->getLabel() ?></th>
                <td><?php echo $this->element->search->renderViewHelper() ?>
                    <?php echo $this->element->search->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->species->getLabel() ?></th>
                <td><?php echo $this->element->species->renderViewHelper() ?>
                    <?php echo $this->element->species->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->strain->getLabel() ?></th>
                <td><?php echo $this->element->strain->renderViewHelper() ?>
                    <?php echo $this->element->strain->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->cellType->getLabel() ?></th>
                <td><?php echo $this->element->cellType->renderViewHelper() ?>
                    <?php echo $this->element->cellType->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->matingType->getLabel() ?></th>
                <td><?php echo $this->element->matingType->renderViewHelper() ?>
                    <?php echo $this->element->matingType->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->citationPubmedId->getLabel() ?></th>
                <td><?php echo $this->element->citationPubmedId->renderViewHelper() ?>
                    <?php echo $this->element->citationPubmedId->renderErrors() ?></td>
            </tr>

        </table>
    </fieldset>
    <br />

    <fieldset>
        <legend>Lifespan</legend>

        <table class="formTable">
            <tr>
                <th><?php echo $this->element->lifespanEffect->getLabel() ?></th>
                <td><?php echo $this->element->lifespanEffect->renderViewHelper() ?>
                    <?php echo $this->element->lifespanEffect->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->lifespanMeasure->getLabel() ?></th>
                <td><?php echo $this->element->lifespanMeasure->renderViewHelper() ?>
                    <?php echo $this->element->lifespanMeasure->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->lifespanUnit->getLabel() ?></th>
                <td><?php echo $this->element->lifespanUnit->renderViewHelper() ?>
                    <?php echo $this->element->lifespanUnit->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->lifespan->getLabel() ?></th>
                <td><?php echo $this->element->lifespanOp->renderViewHelper() ?>
                    <?php echo $this->element->lifespan->renderViewHelper() ?>
                    <?php echo $this->element->lifespan->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->lifespanBase->getLabel() ?></th>
                <td><?php echo $this->element->lifespanBaseOp->renderViewHelper() ?>
                    <?php echo $this->element->lifespanBase->renderViewHelper() ?>
                    <?php echo $this->element->lifespanBase->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->lifespanChange->getLabel() ?></th>
                <td><?php echo $this->element->lifespanChangeOp->renderViewHelper() ?>
                    <?php echo $this->element->lifespanChange->renderViewHelper() ?> %
                    <?php echo $this->element->lifespanChange->renderErrors() ?></td>
            </tr>
        </table>
    </fieldset>
    <br />

    <fieldset>
        <legend>Gene:</legend>
        <table class="formTable">
            <tr>
                <th><?php echo $this->element->geneSymbol->getLabel() ?></th>
                <td><?php echo $this->element->geneSymbol->renderViewHelper() ?>
                    <?php echo $this->element->geneSymbol->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->geneAlleleType->getLabel() ?></th>
                <td><?php echo $this->element->geneAlleleType->renderViewHelper() ?>
                    <?php echo $this->element->geneAlleleType->renderErrors() ?></td>
            </tr>
        </table>
    </fieldset>
    <br />

    <fieldset>
        <legend>Compound:</legend>
        <table class="formTable">
            <tr>
                <th><?php echo $this->element->compoundName->getLabel() ?></th>
                <td><?php echo $this->element->compoundName->renderViewHelper() ?>
                    <?php echo $this->element->compoundName->renderErrors() ?></td>
            </tr>
        </table>
    </fieldset>
    <br />

    <fieldset>
        <legend>Environment:</legend>
        <table class="formTable">
            <tr>
                <th><?php echo $this->element->environmentType->getLabel() ?></th>
                <td><?php echo $this->element->environmentType->renderViewHelper() ?>
                    <?php echo $this->element->environmentType->renderErrors() ?></td>
            </tr>
            <tr>
                <th><?php echo $this->element->environmentDescription->getLabel() ?></th>
                <td><?php echo $this->element->environmentDescription->renderViewHelper() ?>
                    <?php echo $this->element->environmentDescription->renderErrors() ?></td>
            </tr>
        </table>
    </fieldset>
    <br />

    <input type="submit" value="Search" style="width:10em" />
</form>
</div>