<?php $this->headScript()->prependScript('var baseUrl = "'.$this->baseUrl().'";') ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/jquery-1.4.2.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl() . '/scripts/observation/form.js') ?>

<form name="observationForm" action="<?php echo $this->element->getAction() ?>" method="post">

    <?php if ($this->element->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <fieldset style="margin-bottom: 1em; width:44em">
        <legend>Lifespan:</legend>
        <table class="formTable">
            <tr>

                <td style="padding: 0em 2em 0em 0em; width: 8em;">
                    <?php echo $this->element->lifespanEffect->renderLabel() ?>
                    <?php echo $this->element->lifespanEffect->renderViewHelper() ?>
                    <?php echo $this->element->lifespanEffect->renderErrors() ?>
                </td>
                <td style="padding: 0em 2em 0em 0em; width: 8em">
                    <?php echo $this->element->lifespanMeasure->renderLabel() ?>
                    <?php echo $this->element->lifespanMeasure->renderViewHelper() ?>
                    <?php echo $this->element->lifespanMeasure->renderErrors() ?>
                </td>
                <td style="padding: 0em 2em 0em 0em; width: 6em">
                    <?php echo $this->element->lifespanUnit->renderLabel() ?>
                    <?php echo $this->element->lifespanUnit->renderViewHelper() ?>
                    <?php echo $this->element->lifespanUnit->renderErrors() ?>
                </td>

                <td>
                    <table class="formTable">
                        <tr>
                            <th><?php echo $this->element->lifespan->renderLabel() ?></th>
                            <td>
                                <?php echo $this->element->lifespan->renderViewHelper() ?>
                                <?php echo $this->element->lifespan->renderErrors() ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $this->element->lifespanBase->renderLabel() ?></th>
                            <td>
                                <?php echo $this->element->lifespanBase->renderViewHelper() ?>
                                <?php echo $this->element->lifespanBase->renderErrors() ?>
                            </td>
                        </tr>
                        <tr>
                            <th><?php echo $this->element->lifespanChange->renderLabel() ?></th>
                            <td>
                                <?php echo $this->element->lifespanChange->renderViewHelper() ?> %
                                <?php echo $this->element->lifespanChange->renderErrors() ?>
                            </td>
                        </tr>
                     </table>
                </td>

            </tr>
        </table>
    </fieldset>

    <fieldset style="margin-bottom: 1em; width:44em">
        <legend>Organism:</legend>

        <table class="formTable">
            <tr>
                <th><?php echo $this->element->ncbiTaxId->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->ncbiTaxId->renderViewHelper() ?>
                    <a href="#" id="getSpecies">get species</a>
                    <?php echo $this->element->ncbiTaxId->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->species->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->species->renderViewHelper() ?>
                    <?php echo $this->element->species->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->strain->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->strain->renderViewHelper() ?>
                    <?php echo $this->element->strain->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->cellType->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->cellType->renderViewHelper() ?>
                    <?php echo $this->element->cellType->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->matingType->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->matingType->renderViewHelper() ?>
                    <?php echo $this->element->matingType->renderErrors() ?>
                </td>
            </tr>
        </table>
    </fieldset>

 
    <fieldset style="margin-bottom: 1em; width:44em">
        <legend>Citation:</legend>
        <table class="formTable">
            <tr>
                <th><?php echo $this->element->citationPubmedId->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->citationPubmedId->renderViewHelper() ?>
                    <a href="#" id="getCitationData">get citation data</a>
                    <?php echo $this->element->citationPubmedId->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->citationAuthor->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->citationAuthor->renderViewHelper() ?>
                    <?php echo $this->element->citationAuthor->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->citationTitle->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->citationTitle->renderViewHelper() ?>
                    <?php echo $this->element->citationTitle->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->citationSource->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->citationSource->renderViewHelper() ?>
                    <?php echo $this->element->citationSource->renderErrors() ?>
                </td>
            </tr>
            <tr>
                <th><?php echo $this->element->citationYear->renderLabel() ?></th>
                <td>
                    <?php echo $this->element->citationYear->renderViewHelper() ?>
                    <?php echo $this->element->citationYear->renderErrors() ?>
                </td>
            </tr>
        </table>
    </fieldset>


    <fieldset style="margin-bottom: 1em; width:44em;">
        <legend>Interventions:</legend>
        <div class="content">
            <table id="geneTable" class="dataTable">
                <thead>
                    <tr>
                        <th style="width:16em">NCBI Gene ID</th>
                        <th>Symbol</th>
                        <th>Allele</th>
                        <th>Allele Type</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <?php foreach ($this->element->genes as $i => $form): ?>
                    <?php $form->setElementsBelongTo('genes['.$i.']') ?>
                    <tr>
                        <?php echo $this->partial('forms/gene.phtml', array('form' => $form)) ?>
                    </tr>
                <?php endforeach ?>
            </table>
            <input type="hidden" id="iGene" value="<?php echo count($this->element->genes) ?>" />
            <div style="margin: 0.25em 0">
                <a href="#" class="addGene add">add gene</a>
            </div>
            <br />
            
            <table id="compoundTable" class="dataTable">
                <thead>
                    <tr>
                        <th style="width:16em">NCBI Compound ID</th>
                        <th>Name</th>
                        <th>Quantity</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <?php foreach ($this->element->compounds as $i => $form): ?>
                    <?php $form->setElementsBelongTo('compounds['.$i.']') ?>
                    <tr>
                        <?php echo $this->partial('forms/compound.phtml', array('form' => $form)) ?>
                    </tr>
                <?php endforeach ?>
            </table>
            <input type="hidden" id="iCompound" value="<?php echo count($this->element->compounds) ?>" />
            <div style="margin: 0.25em 0">
                <a href="#" class="addCompound add">add compound</a>
            </div>
            <br />

            <table id="environmentTable" class="dataTable">
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Description</th>
                        <th>Delete</th>
                    </tr>
                </thead>
                <?php foreach ($this->element->environments as $i => $form): ?>
                    <?php $form->setElementsBelongTo('environments['.$i.']') ?>
                    <tr>
                        <?php echo $this->partial('forms/environment.phtml',  array('form' => $form)) ?>
                    </tr>
                <?php endforeach ?>
            </table>
            <input type="hidden" id="iEnvironment" value="<?php echo count($this->element->environments) ?>" />
            <div style="margin: 0.25em 0">
                <a href="#" class="addEnvironment add">add environment</a>
            </div>
        </div>
    </fieldset>


    <fieldset style="margin-bottom: 1em; width:44em">
        <legend>Observation Details:</legend>
        <table class="formTable">
            <tr>
                <th>Description:</th>
                <td>
                    <?php echo $this->element->body->renderViewHelper() ?>
                    <br />
                    <?php echo $this->element->body->renderErrors() ?>
                    <div style="margin-bottom: 0.5em">
                        Include any additional information on non-aging related phenotypes,
                        experimental conditions, wild-type lifespan, etc...<br />
                    </div>
                </td>
            </tr>

            <tr>
                <th><?php echo $this->element->temperature->renderLabel() ?></th>
                <td style="vertical-align:middle">
                    <?php echo $this->element->temperature->renderViewHelper() ?> &deg;C
                    <?php echo $this->element->temperature->renderErrors() ?>
                </td>
            </tr>
        </table>
    </fieldset>


    <?php if ($this->element->canPublish() === true): ?>
        <fieldset style="margin-bottom: 1em; width:44em">
            <legend>Revision:</legend>
            
            <table class="formTable">
                <tr>
                    <th><?php echo $this->element->status->renderLabel() ?></th>
                    <td>
                        <?php echo $this->element->status->renderViewHelper() ?>
                        <?php echo $this->element->status->renderErrors() ?>
                    </td>
                </tr>

                <tr>
                    <th><?php echo $this->element->reviewerComment->renderLabel() ?></th>
                    <td>
                        <?php echo $this->element->reviewerComment->renderViewHelper() ?>
                        <?php echo $this->element->reviewerComment->renderErrors() ?>
                    </td>
                </tr>
            </table>
        </fieldset>
    <?php endif ?>

    <?php echo $this->element->id->renderViewHelper() ?>
    <?php echo $this->element->Submit ?>
</form>


<div id="geneTemplate" style="display:none">
    <table>
        <tr>
            <?php echo $this->partial('forms/gene.phtml', array(
                'form' => new Application_Form_ObservationFormGeneForm()
            )) ?>
        </tr>
    </table>
</div>

<div id="compoundTemplate" style="display:none">
    <table>
        <tr>
            <?php echo $this->partial('forms/compound.phtml', array(
                'form' => new Application_Form_ObservationFormCompound()
            )) ?>
        </tr>
    </table>
</div>

<div id="environmentTemplate" style="display:none">
    <table>
        <tr>
            <?php echo $this->partial('forms/environment.phtml', array(
                'form' => new Application_Form_ObservationFormEnvironment()
            )) ?>
        </tr>
    </table>
</div>