<div style="width:23%; float:left">
        <h2>About</h2>
        <p>Sageweb Lifespan Observation database collects published lifespan
        data across multiple species. Users are allowed to submit new data
        as well as edit existing data.</p>
        <br />

        <h2>Download</h2>
        <p>The entire database is available for download in various formats.</p>
        <dl>
            <dt><a href="<?php echo $this->baseUrl('search') . '?format=xml' ?>"
                >XML</a></dt>
                <dd>The standard data exchange format.</dd>
            <dt><a href="<?php echo $this->baseUrl('search') . '?format=yml' ?>"
                >YAML</a></dt>
                <dd>A more human readable XML variant.</dd>
            <dt><a href="<?php echo $this->baseUrl('search') . '?format=csv' ?>"
                >CSV</a></dt>
                <dd>Flat comma-delimited file readable by Excel.</dd>
        </dl>
        <br />

        <h2>Growth</h2>
        <table class="dataTable" style="width:100%" >
            <tr>
                <th>Time</th>
                <th style="text-align:center">Count</th>
            </tr>
            <?php foreach ($this->growthRows as $timeFrame => $count): ?>
                <tr>
                    <td><em><?php echo $timeFrame ?></em></td>
                    <td style="text-align:center"><?php echo $count ?></td>
                </tr>
            <?php endforeach ?>
        </table>
        <br />
</div>

<div style="width:50%; padding-left:1em; padding-right:1em; float: left;">
    <map name="speciesMap" id="speciesMap">
        <area alt="Homo sapiens" href="<?php echo $this->url(array(
            'controller' => 'search', 'action' => 'index',
            't' => 'observations', 'q' => 'species:"Homo sapiens"'
            )) ?>" shape="rect" coords="103,33,217,135" title="Homo sapiens" />
        <area alt="Pan troglodytes" href="<?php echo $this->url(array(
            'controller' => 'search', 'action' => 'index',
            't' => 'observations','q' => 'species:"Pan troglodytes"'
            )) ?>" shape="rect" coords="250,100,350,200" title="Pan troglodytes" />
        <area alt="Mus musculus" href="<?php echo $this->url(array(
            'controller' => 'search', 'action' => 'index',
            't' => 'observations','q' => 'species:"Mus musculus"'
            )) ?>" shape="rect" coords="44,218,146,311" title="Mus musculus" />
        <area alt="Drosophila melanogaster" href="<?php echo $this->url(array(
            'controller' => 'search', 'action' => 'index',
            't' => 'observations','q' => 'species:"Drosophila melanogaster"'
            )) ?>" shape="rect" coords="283,294,410,400" title="Drosophila melanogaster" />
        <area alt="Caenorhabditis elegans" href="<?php echo $this->url(array(
            'controller' => 'search', 'action' => 'index',
            't' => 'observations','q' => 'species:"Caenorhabditis elegans"'
            )) ?>" shape="rect" coords="243,469,345,570" title="Caenorhabditis elegans" />
        <area alt="Saccharomyces cerevisiae" href="<?php echo $this->url(array(
            'controller' => 'search', 'action' => 'index',
            't' => 'observations','q' => 'species:"Saccharomyces cerevisiae"'
            )) ?>" shape="rect" coords="61,437,177,527" title="Saccharomyces cerevisiae" />
    </map>
    <img src="<?php echo $this->baseUrl('images/dbase_image.png') ?>" alt=""
         usemap="#speciesMap" style="border:none" />

<?php /**
    <?php if (count($this->featuredObservations) > 0): ?>
        <h2 style="margin-top:1em;text-align:center">Featured Observations</h2>
        <?php foreach ($this->featuredObservations as $observation): ?>
            <hr class="separator" />
            <div style="margin-top:1em; margin-bottom: 1em">
                <em><?php echo $this->escape($observation->species) ?></em>
                <?php if (!empty($observation->strain)): ?>
                    (<?php echo $this->escape($observation->strain) ?>)
                <?php endif ?>
                <br />
                <?php echo $observation->body ?>
                <a href="<?php echo $this->url(array(
                    'controller' => 'observations',
                    'action' => 'show',
                    'id' => $observation->id
                )) ?>">view more...</a>
            </div>
        <?php endforeach ?>
    <?php endif ?>


    <?php if ($this->lastObservation !== null): ?>
        <h2 style="margin-top:1em;text-align:center">Most Recent Observation</h2>
        <hr class="separator" />
        <div style="margin: 1em 0">
            <em><?php echo $this->escape($this->lastObservation->species) ?></em>
            <?php if (!empty($this->lastObservation->strain)): ?>
                (<?php echo $this->escape($this->lastObservation->strain) ?>)
            <?php endif ?>
            <br />
            <?php echo $this->lastObservation->body ?>
            <a href="<?php echo $this->url(array(
                'controller' => 'observations',
                'action' => 'show',
                'id' => $this->lastObservation->id
            )) ?>">view more...</a>
        </div>
    <?php endif ?>
    <br />
    <br />
*/ ?>
</div>

<div style="width: 23%; float:left;">
        <h2>Summary</h2>
        <table class="dataTable" style="width:100%" >
            <tr>
                <th>Species</th>
                <th style="text-align:center">Count</th>
            </tr>
            <?php foreach ($this->statistics as $row): ?>
                <tr>
                    <td><em><?php echo $this->escape($row['short_species']) ?></em></td>
                    <td style="text-align:center">
												<a href="<?php echo $this->url(array(
													'controller' => 'search', 
													'action' => 'index',
													't' => 'observations',
													'q' => 'species:"' . $row['species'] . '"'
													)) ?>"
												><?php echo $row['observationCount'] ?>
										</td>
                </tr>
            <?php endforeach ?>
        </table>
        <br />

        <h2>Contributers</h2>
        <table class="dataTable" style="width:100%" >
            <tr>
                <th>Username</th>
                <th style="text-align:center">Count</th>
            </tr>
            <?php foreach ($this->topContributers as $row): ?>
                <tr>
                    <td><em><?php echo $this->escape($row['username']) ?></em></td>
                    <td style="text-align:center">
											<a href="<?php echo $this->url(array(
												'controller' => 'search', 
												'action' => 'index',
												't' => 'observations',
												'q' => 'submittedBy:"' . $row['username'] . '"'
												)) ?>"
											><?php echo $row['count'] ?></a></td>
                </tr>
            <?php endforeach ?>
        </table>
				<br />

</div>
