<h1>Observation <?php echo $this->observationId ?> Revisions</h1>

<table class="dataTable">
    <thead>
        <tr>
            <th>Action</th>
            <th>Requsted By</th>
            <th>Requested At</th>
            <th>Approved By</th>
            <th>Approved At</th>
            <th>Status</th>
            <th>More</th>
        </tr>
    </thead>

    <tbody>
        <?php foreach ($this->revisions as $revision): ?>
            <tr>
                <td><?php echo $revision->action ?></td>
                <td><?php echo $revision->requestedBy ?></td>
                <td><?php echo $revision->requestedAt ?></td>
                <td><?php echo $revision->reviewedBy ?></td>
                <td><?php echo $revision->reviewedAt ?></td>
                <td><?php echo $revision->status ?></td>
                <td>
                    <a href="<?php echo $this->baseUrl().
                        '/observations/revision/id/'.$revision->id ?>"
                        >View</a>
                </td>
            </tr>
        <?php endforeach ?>
    </tbody>
</table>

