<?php echo $this->partial('manage/_tabs.phtml', array(
    'tabs' => $this->tabs
    )) ?>

<a href="<?php echo $this->url(array('format' => 'rss')) ?>"
   class="rss" style="float:right"
   >Subscribe to RSS</a>

<h1>Comments Pending Review</h1>

<table class="dataTable">
    <tr>
        <th></th>
        <th>Comment ID</th>
        <th>Parent Table</th>
        <th>Parent ID</th>
        <th>Author</th>
        <th>Created At</th>
        <th>Body</th>
        <th>View</th>
    </tr>

    <?php foreach ($this->comments as $comment): ?>
        <tr>
            <td></td>
            <td><?php echo $comment->id ?></td>
            <td><?php echo $comment->parentTable ?></td>
            <td><?php echo $comment->parentId ?></td>
            <td><?php echo $this->escape($comment->author) ?></td>
            <td><?php echo $comment->createdAt ?></td>
            <td><?php echo $this->escape($comment->body) ?></td>
            <td><a href="<?php echo $this->url(array(
                'controller' => 'comments',
                'action' => 'revision',
                'id' => $revision->id
                )) ?>">View</a></td>
        </tr>
    <?php endforeach ?>
</table>