<table class="dataTable" style="width:100%">
    <thead>
        <tr>
            <th>Species</th>
            <th>Symbol</th>
            <th>Locus Tag</th>
            <th>NCBI Gene ID</th>
            <th>Observations</th>
            <th style="text-align:center">More</th>
        </tr>
    </thead>

    <?php foreach ($this->rows as $row): ?>
        <tr>
            <td><?php echo $this->escape($row['species']) ?></td>
            <td><?php echo $this->escape($row['symbol']) ?></td>
            <td><?php echo $this->escape($row['locusTag']) ?></td>
            <td><?php echo $this->escape($row['ncbiGeneId']) ?></td>
            <td><?php echo $this->escape($row['count']) ?></td>
            <td style="text-align:center">
                <a href="<?php echo $this->url(
                    array('controller' => 'genes', 'action' => 'show',
                        'id' => $row['ncbiGeneId'])) ?>">View</a>
            </td>
        </tr>
    <?php endforeach ?>
</table>
