<?php

/**
 * CommentLinkTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CommentLinkTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObservationRevisionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CommentLink');
    }
}