<?php

/**
 * CompoundSynonymTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompoundSynonymTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompoundSynonymTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompoundSynonym');
    }
}