<?php

/**
 * ObservationGeneTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObservationGeneTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObservationGeneTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObservationGene');
    }
}