<?php

/**
 * ObservationEnvironmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObservationEnvironmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObservationEnvironmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ObservationEnvironment');
    }

    public static function getTypes()
    {
        $q = Doctrine_Query::create()->from('ObservationEnvironment oe')
            ->select('DISTINCT oe.type');
        $rows = $q->execute(array(), Doctrine_Core::HYDRATE_ARRAY);

        $types = array();
        foreach ($rows as $row) {
            $types[] = $row['type'];
        }
        return $types;
    }
}