<?php

/**
 * Observation
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Observation extends BaseObservation
{
    public static function getLifespanEffects()
    {
        return array(
            'increased'  => 'Increased',
            'decreased'  => 'Decreased',
        );
    }

    public static function getLifespanMeasures()
    {
        return array(
            'mean'       => 'Mean',
            'median'     => 'Median',
            'max'        => 'Max',
            'individual' => 'Individual',
        );
    }

    public static function getLifespanUnits()
    {
        return array(
            'days' => 'Days',
            'years' => 'Years',
            'divisions' => 'Divisions',
            'si' => 'SI',
        );
    }

    public static function getMatingTypes($species = null)
    {
        return array(
            'male' => 'Male',
            'female' => 'Female',
            'hermaphrodite' => 'Hermaphrodite',
            'mata' => 'MATa',
            'matalpha' => 'MATalpha',
            'diploid' => 'Diploid',
        );
    }

    public static function getStatusChoices()
    {
        return array(
            'public'    => 'Public',
            'held'      => 'Held',
            'deleted'   => 'Deleted',
        );
    }

    public function preSave($event)
    {
        parent::preSave($event);

        $this->normalizeFields();

        if ($this->status == null) {
            $this->status = 'public';
        }
        $this->geneCount = count($this->genes);
        $this->compoundCount = count($this->compounds);
        $this->environmentCount = count($this->environments);
    }

    /**
     * Normalize dependent fields to prevent inconsistencies. This should be
     * replaced in the future by code that notifies the suNbmitter of inconsistencies
     * rather than fix them without warning as done here.
     */
    private function normalizeFields() {
        // compute lifespan change off lifespans if we can
        $lifespan = $this->get('lifespan');
        $lifespanBase = $this->get('lifespanBase');
        if ($lifespan !== null && $lifespanBase !== null) {
            $percentChange =  ($lifespan - $lifespanBase) / $lifespanBase * 100;
            $this->set('lifespanChange', $percentChange);
        }

        // compute lifespan effect off lifespan change if we can
        $lifespanChange = $this->get('lifespanChange');
        if ($lifespanChange !== null) {
            if ($lifespanChange > 0) {
                $this->set('lifespanEffect', 'increased');
            }
            if ($lifespanChange < 0) {
                $this->set('lifespanEffect', 'decreased');
            }
        }
    }

}
