<?php

/**
 * TaxonomySynonymTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomySynonymTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxonomySynonymTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('TaxonomySynonym');
    }
}