<?php

/**
 * TaxonomyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class TaxonomyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object TaxonomyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Taxonomy');
    }

    public static function import($ncbiTaxId)
    {
        // import new gene information
        $data = Application_Model_Service_Ncbi::getTaxonData($ncbiTaxId);
        if (!$data) {
            return null;
        }

        $taxonomy = new Taxonomy();
        $taxonomy->name = $data['name'];
        $taxonomy->ncbiTaxId = $data['taxon_id'];
        $taxonomy->save();

        // fetch synonyms
        $rows = Application_Model_Service_Ncbi::getTaxonSynonyms($ncbiTaxId);
        foreach ($rows as $row) {
            $taxonomySynonym = new TaxonomySynonym();
            $taxonomySynonym->taxonomyId = $taxonomy->id;
            $taxonomySynonym->synonym = $row['synonym'];
            $taxonomySynonym->type = $row['class'];
            $taxonomySynonym->save();

            $taxonomy->synonyms[] = $taxonomySynonym;
        }

        return $taxonomy;
    }

}