<?php

/**
 * ObservationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ObservationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ObservationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Observation');
    }

    /**
     * Returns a observation with interventions and revisions
     */
    public static function getObservation($id)
    {
        $q = Doctrine_Query::create()->from('Observation o')
            ->leftJoin('o.genes g')
            ->leftJoin('o.compounds c')
            ->leftJoin('o.environments e')
            ->leftJoin('o.taxonomy t')
            ->where('o.id = ?', $id);
        $observation = $q->fetchOne();
        return $observation;
    }

    public static function getSpeciesChocies()
    {
        $q = Doctrine_Query::create()->from('Observation o')
            ->select('DISTINCT o.species')
            ->orderBy('o.species ASC');

        $choices = array();
        foreach ($q->fetchArray() as $row) {
            $species = $row['species'];
            $choices[$species] = $species;
        }
        return $choices;
    }

    public static function getMostRecentObservation()
    {
        $q = Doctrine_Query::create()->from('Observation o')
            ->leftJoin('o.genes g')
            ->leftJoin('o.compounds c')
            ->leftJoin('o.environments e')
            ->leftJoin('o.taxonomy t')
            ->where('o.createdAt IS NOT NULL')
            ->orderBy('o.createdAt DESC')
            ->limit(1);
        $observation = $q->fetchOne();
        return $observation;
    }
}