<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Lifespan Observations Database</title>
    <?php $this->headLink()->prependStylesheet($this->baseUrl().'/styles/global.css') ?>
    <?php echo $this->headLink() ?>
    <?php echo $this->headScript() ?>
</head>

<body>
    <div id="viewport">

        <div id="top-bar">
            <div id="global-crumb">
                <a href="http://sageweb.org/">Sageweb.org</a>
                &gt; Tools
            </div>
            <div id="user-menu">
                <?php if (!Zend_Auth::getInstance()->hasIdentity()): ?>
                    <a href="http://sageweb.org/user/register">Register</a>
                    or
                    <a href="<?php echo $this->baseUrl('account/login') 
                            . '?destination=' . $this->url() ?>">Sign In</a>
                <?php else: ?>
                    <a href="<?php echo $this->baseUrl('observations/new') ?>">New</a>
                    <a href="<?php echo $this->baseUrl('observations/upload') ?>">Upload</a>
                    <a href="<?php echo $this->baseUrl('account/logout')
                            . '?destination=' . $this->url() ?>">Logout</a>
                <?php endif ?>
            </div>
        </div>

        <div id="header">
            <div style="float:left">
                <a href="<?php echo $this->baseUrl() ?>/">Lifespan Observations Database</a>
            </div>
        </div>

        <div id="menu">
            <div style="float:left">
                <form action="<?php echo $this->baseUrl('search') ?>" method="get"
                    style="display:inline">
                    
                    Find: <?php echo $this->formText('q', $this->layout()->q, array('size' => '50')) ?>
                    <input type="submit" value="Search" />
                </form>
                <a href="<?php echo $this->baseUrl('search/advanced') ?>">advanced...</a>
            </div>

            <div style="clear:both"></div>
        </div>

        <div id="content">
            <?php echo $this->layout()->content; ?>
        </div>

        <div id="footer">
            <p>
                Olsen B, Kaeberlein M (<?php echo date('Y') ?>).
                Lifespan Observation Database: http://sageweb.org/lifespandb</p>
        </div>
    </div>
</body>
</html>





