<?php echo $this->partial('manage/_tabs.phtml', array(
    'tabs' => $this->tabs
    )) ?>

<a href="<?php echo $this->url(array('format' => 'rss')) ?>"
   class="rss" style="float:right"
   >Subscribe to RSS</a>

<h1>Observation Revisions Pending Review</h1>

<table class="dataTable" style="text-align:center">
    <tr>
        <th>Revision ID</th>
        <th>Observation ID</th>
        <th>Action</th>
        <th>Requested By</th>
        <th>Requested At</th>
        <th>View</th>
    </tr>

    <?php foreach ($this->revisions as $revision): ?>
        <tr>
            <td><?php echo $revision->id ?></td>
            <td><?php echo $revision->observationId ?></td>
            <td><?php echo $revision->action ?></td>
            <td><?php echo $revision->requestedBy ?></td>
            <td><?php echo $revision->requestedAt ?></td>
            <td><a href="<?php echo $this->url(array(
                'controller' => 'observations',
                'action' => 'revision',
                'id' => $revision->id
                )) ?>">View</a></td>
        </tr>
    <?php endforeach ?>
</table>