<h1>Update Observations Database</h1>

<?php if ($this->addedCount > 0): ?>
    <div style="color:green; margin-bottom:1em">
        <?php echo $this->addedCount ?> observations updated successfully.
    </div>
<?php endif ?>

<form enctype="application/x-www-form-urlencoded" action="" method="post">
    <?php if (count($this->heldItems) > 0): ?>
        <div style="float:right; width: 48%; margin-right:10px;">
            <p>Below is the combined YAML for all rejected observations:</p>
            <textarea name="heldYamlInput" cols="80" rows="20" nowrap wrap="off"
                spellcheck="false" style="width: 100%; display:block; margin-top:1em; white-space:nowrap"
                ><?php echo $this->heldYaml ?></textarea>
        </div>

        <div style="width: 48%">
            <?php foreach ($this->heldItems as $heldItem): ?>
                <div style="margin-bottom:1em">
                    <p>Observation could not be updated:</p>
                    <ul style="color:red">
                        <?php foreach ($heldItem['messages'] as $message): ?>
                            <li><?php echo $message ?></li>
                        <?php endforeach ?>
                    </ul>
                    <textarea name="yamlInputs[]" cols="90" rows="15" nowrap wrap="off"
                        spellcheck="false" style="width:100%; display:block; margin-top:1em; white-space:nowrap"
                        ><?php echo $heldItem['yaml'] ?></textarea>
                </div>
            <?php endforeach ?> 

            <?php echo $this->formSubmit('resubmit', 'Re-Submit',
                array('style' => 'width:10em') ) ?>

        </div>
    <?php else: ?>
        <p>Update entries in the database using the YAML data exchange format:</p>

        <textarea name="yamlInput" cols="90" rows="20" nowrap wrap="off"
            spellcheck="false"  style="width:50%; display:block; margin: 1em 0 2em 0; white-space:nowrap"
            ><?php echo $this->inputYaml ?></textarea>
        <?php echo $this->formSubmit('submit', 'Submit',
                array('style' => 'width:10em') ) ?>
    <?php endif ?>
</form>



