<form id="commentForm" name="commentForm"
      action="<?php echo $this->element->getAction() ?>" method="post">

    <?php if ($this->element->isErrors()): ?>
        <p style="color:red; margin-bottom: 1em;">The form had some errors. Please correct them below.</p>
    <?php endif ?>

    <div>
        <p>Leave a comment:</p>
        <?php echo $this->element->body->renderErrors() ?>
        <?php echo $this->element->body->renderViewHelper() ?>
    </div>

    <?php echo $this->element->Submit->renderViewHelper() ?>
</form>
