<td >
    <?php echo $this->form->id ?>
    <span style="white-space:nowrap;">
        <?php echo $this->form->ncbiGeneId->renderViewHelper() ?>
        <a href="#" class="getGeneSymbol">get&nbsp;symbol</a>
    </span>
    <?php echo $this->form->ncbiGeneId->renderErrors() ?>
</td>
<td><?php echo $this->form->symbol ?></td>
<td><?php echo $this->form->allele ?></td>
<td><?php echo $this->form->alleleType ?></td>
<td style="text-align: center; padding-top:8px">
    <?php echo $this->form->isDeleted ?>
</td>
