<?php foreach ($this->filters as $fieldName => $filters): ?>
    <div style="margin-bottom: 0.5em">
        <?php echo $fieldName ?>:<br />
        <?php foreach ($filters as $filter): ?>
            <a href="<?php echo $this->url(array('q' => $filter['q'])) ?>"
                ><?php echo $filter['label'] ?></a>
               <span class="resultCount">(<?php echo $filter['count'] ?>)</span>
            <br />
        <?php endforeach ?>
    </div>
<?php endforeach ?>