<?php foreach ($this->filters as $fieldName => $filters): ?>
    <div style="margin-bottom: 0.5em">
        <?php echo $fieldName ?>:<br />
        <?php foreach ($filters as $filter): ?>
            <a href="<?php echo $this->url(array('t' => $this->type, 'q' => $filter['q'])) ?>"
                ><?php echo $filter['label'] ?></a>
               (<?php echo $filter['count'] ?>)
               <br />
        <?php endforeach ?>
    </div>
<?php endforeach ?>