<?php

header("Content-type: application/csv");
header("Content-Disposition: attachment; filename=search-results.csv");
header("Pragma: no-cache");
header("Expires: 0");

$line2 = join(',', array(
   "observation","","","","","","","","","","","","","","","","",
   "gene","","","compound","","","environment"
    ));
echo $line1, "\n";

$line2 = join(',', array(
    "id","lifespanEffect","lifespanMeasure","lifespanUnit","lifespan",
    "lifespanBase","lifespanChange","species","strain","cellType",
    "matingType","citationPubmedId","citationAuthor","citationTitle",
    "citationSource","citationYear","body","ncbiGeneId","symbol",
    "alleleType","ncbiCompoundId","name","quantity","type","body"
));
echo $line2, "\n";

foreach ($this->rows as $row) {
    $observationData = array(
        $row['id'],
        $row['lifespanEffect'],
        $row['lifespanMeasure'],
        $row['lifespanUnit'],
        $row['lifespan'],
        $row['lifespanBase'],
        $row['lifespanChange'],
        $this->quoteCsv($row['species']),
        $this->quoteCsv($row['strain']),
        $this->quoteCsv($row['cellType']),
        $this->quoteCsv($row['matingType']),
        $row['citationPubmedId'],
        $this->quoteCsv($row['citationAuthor']),
        $this->quoteCsv($row['citationTitle']),
        $this->quoteCsv($row['citationYear']),
        $this->quoteCsv($row['body']),
    );

    $interventionCount = 0;
    foreach ($row['genes'] as $gene) {
        $geneData = array(
            $gene['ncbiGeneId'],
            $this->quoteCsv($gene['symbol']),
            $this->quoteCsv($gene['alleleType']),
        );
        echo join(',', $observationData), ',', join(',', $geneData), "\n";
        $interventionCount++;
    }

    foreach ($row['compounds'] as $compound) {
        $compoundData = array(
            $compound['ncbiCompoundId'],
            $this->quoteCsv($compound['name']),
            $this->quoteCsv($compound['quantity']),
        );
        echo join(',', $observationData), ',', join(',', $compoundData), "\n";
        $interventionCount++;
    }

    foreach ($row['environments'] as $environment) {
        $environmentData = array(
            $this->quoteCsv($environment['type']),
            $this->quoteCsv($environment['body']),
        );
        echo join(',', $observationData), ',', join(',', $environmentData), "\n";
        $interventionCount++;
    }

    if ($interventionCount == 0) {
        echo join(',', $observationData), "\n";
    }
}