<div style="width:23%; float:left">
    <div style="padding:10px">
        <h2>About Database</h2>
        <p>Sageweb Lifespan Observation database collects published lifespan
        data across multiple species. Users are allowed to submit new data
        as well as edit existing data.</p>
        <br />

        <h2>New Updates</h2>
        <ul>
            <li><strong><?php echo date('Y-m-d') ?></strong><br />
                new updates made to gene, compound, and search pages</li>
            <li><strong>2010-06-08</strong><br />
                gene data from AGEID database imported</li>
            <li><strong>2010-06-02</strong><br />
                database application launched on sageweb.org</li>
        </ul>
        <br />
    </div>
</div>