<?php $this->headScript()->appendFile($this->baseUrl().'/scripts/jquery-1.4.2.js') ?>
<?php $this->headScript()->appendFile($this->baseUrl().'/scripts/compound.js') ?>

<h1 style="margin-bottom:0.25em">
    Observations on Compound: <?php echo $this->compound['name'] ?>
</h1>

<div class="sidepane">
    <div class="sidepane-header">
        <div style="float:right; margin-right:6px; margin-top:3px">
            <img src="<?php echo $this->baseUrl('images/hide.png') ?>" alt="" />
        </div>
        Observations on Related Genes
    </div>
    <div class="sidepane-bottom" style="text-align:center">
        <?php if (count($this->relatedGenes) > 0): ?>
        <?php else: ?>
            None found...
        <?php endif ?>
    </div>
</div>

<div class="sidepane">
    <div class="sidepane-header">
        <div style="float:right; margin-right:6px; margin-top:3px">
            <img src="<?php echo $this->baseUrl('images/hide.png') ?>" alt="" />
        </div>
        Observations on Related Compounds
    </div>
    <div class="sidepane-bottom" style="text-align:center">
        <?php if (count($this->relatedCompounds) > 0): ?>
        <?php else: ?>
            None found...
        <?php endif ?>
    </div>
</div>

<div class="sidepane">
    <div class="sidepane-header">
        <div style="float:right; margin-right:6px; margin-top:3px">
            <img src="<?php echo $this->baseUrl('images/hide.png') ?>" alt="" />
        </div>
        User Comments
    </div>
    <div class="sidepane-bottom" style="text-align:center">
        <?php if (count($this->comments) > 0): ?>
        <?php endif ?>
        <p style="text-align:center">
            <a href="<?php echo $this->baseUrl('compound/comment')
            .'/id/'.$this->compound['ncbiCompoundId'] ?>">Add a comment...</a>
        </p>
    </div>
</div>

<div class="compound" style="margin-right:420px;">
    <table class="verticalTable">
        <tr>
            <th>Name</th>
            <td><?php echo $this->escape($this->compound['name']) ?></td>
        </tr>
        <tr>
            <th>Synonyms</th>
            <td>
                <?php if (count($this->synonyms) > 0): ?>
                    <?php echo $this->escape(join(', ', $this->synonyms)) ?>
                <?php endif ?>
            </td>
        </tr>
        <tr>
            <th>Description</th>
            <td><?php echo $this->escape($this->compound['description']) ?></td>
        </tr>

        <tr>
            <th>Ncbi Compound</th>
            <td>
                <?php if (isset($this->compound['ncbiCompoundId'])): ?>
                    <a href="http://pubchem.ncbi.nlm.nih.gov/summary/summary.cgi?cid=<?php
                        echo $this->compound['ncbiCompoundId'] ?>"
                        ><?php echo $this->escape($this->compound['ncbiCompoundId']) ?></a>
                <?php endif ?>
            </td>
        </tr>

        <tr>
            <th>Links</th>
            <td>
                <?php foreach ($this->links as $label => $url): ?>
                    <a href="<?php echo $url ?>"><?php echo $label ?></a>
                <?php endforeach ?>
            </td>
        </tr>
    </table>

    <br />

    <h2>Lifespan Observations:</h2>
    <?php if (count($this->observations) > 0): ?>
        <?php echo $this->partial('tables/observation.phtml',
            array('rows' => $this->observations)); ?>
    <?php else: ?>
        <p>No lifespan observations for this compound.</p>
    <?php endif ?>

    <br />


    <h2>Compound Annotations:</h2>

    <div class="collapsable" style="margin-top: 1em">
        <h2 class="region collapseable expanded">Interacting Proteins</h2>
        <div class="content">
            <p>Not available.</p>
        </div>
    </div>
</div>

